/**
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not
 * exceed four million, find the sum of the even-valued terms.
 *
 */

#include <iostream>

int main(int argc, char *argv[])
{
  int n2=1;
  int n1=1;
  const int MAX = 4000000;
  int sum = 0;

  while (n1 < MAX) {
    int n = n2 + n1;
    n2 = n1;
    n1 = n;
    if (n %2 == 0) {
     sum += n;
    }
  }
  std::cout << "Somme = " << sum << std::endl;
  return 0;
}
